######
## https://github.com/forcedotcom/sfdx-circleci-org/blob/master/.circleci/config.yml
######

auth: &auth
    run:
      name: Authorize Target Deployment Org
      context: DEV
      command: |
        #Authorize target org
        sfdx force:auth:jwt:grant --instanceurl $ENDPOINT --clientid $CONSUMER_KEY --jwtkeyfile jwt/server.key --username $USER_NAME --setalias dev -d

createSFDX: &createSFDX
    run:
      name: "Create SFDX Folder" 
      command: |
        mkdir sfdx

decryptKey: &decryptKey
    run:
      name: Decrypt server key
      command: |
        #Decrypt server key
        openssl enc -nosalt -aes-256-cbc -d -in jwt/server.key.enc -out jwt/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
      
deploy: &deploy
    run:
      name: Deploy to Target Deployment Org
      command: |
        #Deploy to target deployment org and run unit tests. 
        sfdx force:mdapi:deploy --wait 10 --deploydir $DEPLOYDIR --targetusername UAT --testlevel $TESTLEVEL
      
      #Example shows how to run a check only deploy.
      #sfdx force:mdapi:deploy --checkonly --wait 10 --deploydir $DEPLOYDIR --targetusername UAT --testlevel $TESTLEVEL

build_docker: &build_docker
    working_directory: '~/project'
    build:
      docker:
        - image: circleci/node:8.9.4
      environment:
        # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
        # and https://developer.salesforce.com/media/salesforce-cli/manifest.json

        # Variables used in build steps
        - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        - TESTLEVEL: RunLocalTests
        - DEPLOYDIR: src
  
deploySource: &deploySource
  run:
    name: Deploying project via source api
    command: |
      cd project/
      sfdx force:source:deploy -u dev -p force-app/ -w 8

getCLI: &getCLI
    run:
      name: Download CLI
      command: |
        # Download cli
        wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1

installCLI: &installCLI
    run:
      name: Install CLI
      command: |
        # Install the cli
        ./sfdx/install
        sfdx

run_local_tests: &run_local_tests 
  run:
    name: Run all local tests
    command: |
      mkdir test
      sfdx force:apex:test:run -l RunLocalTests -r human -c -d test -u dev

deployDev:
  <<: *build_docker
  steps:
      - checkout #inbuilt command through Circle to checkout the repo you authd 
      - *createSFDX
      - *getCLI
      - *installCLI
      - *decryptKey
      - *auth
      - *deploySource

version: 1
jobs: 
  #executer step <<: *build_docker 
  build:
    docker:
      - image: circleci/node:8.9.4
    environment:
      # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
      # and https://developer.salesforce.com/media/salesforce-cli/manifest.json

      # Variables used in build steps
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      - TESTLEVEL: RunLocalTests
      - DEPLOYDIR: src

    steps:
        - checkout #inbuild command through Circle to checkout the repo you authd 
        - *createSFDX
        - *getCLI
        - *installCLI
        - *decryptKey
        - *auth
        - *run_local_tests
        - *deployDev:
            requires: [ run_local_tests ]
            context: DEV
            filters:
              branches:
                only: master
        
        - approveDev:
            requires: [ deployDev ]
            type: approval
