
auth: &auth
  run:
    name: 'sign into salesforce'
      command: 'bin/'

request_docker: &request_docker
  working_directory: '~/project'
    docker:
      - image: 'create docker image'

source_deploy: &source_deploy
  run:
    name: 'deploy using source deploy'
      command: 'sfdx force:source:deploy -p deploydir/ -u "${ALIAS}"'

specify_path: &specify_path
  persist_to_workspace:
    root: '~'
    paths: [ 'project' ]

run_local_test: &run_local_test
  run:
    name: 'running all local tests'
      command: 'sfdx force:apex:test:run -l  RunLocalTests --verbose -a "${ALIAS}"'

jobs:
  spin_up_env:
    - *request_docker
    - *auth


deployDev:
  <<: *source_deploy
deployTest:
  <<: *source_deploy
deployBeta:
  <<: *source_deploy

workflows:
  pipeline:
    jobs:
      - run_local_tests:
        context: DEV

      - static_code_analysis:
        requires: [ run_local_tests ]

      - deployDEV:
          requires: [ run_local_tests ]
          context: DEV
            filters:
              branches:
                only: playground

      - ApproveDEV:
        requires: [ deployDEV ]
          type: approval

      - deployTest:
          requires: [ ApproveDEV ]
          context: TEST
                
      - ApproveTEST:
        requires: [ deployTEST ]
          type: approval

      - deployBETA:
          requires: [ ApproveTEST ]
          context: BETA